#ifndef PH_CONFIG_H
#define PH_CONFIG_H

#define PH_CHANNEL_COUNT (4U)
#define PH_CHANNEL_MASK_VALID (0x0FU)
#define PH_CHANNEL_NONE (0xFFU)

#define PH_DEFAULT_RETRY_LIMIT (2U)
#define PH_DEFAULT_SETTLE_TIME_MS (100U)
#define PH_DEFAULT_ADC_TIMEOUT_MS (50U)
#define PH_DEFAULT_SAMPLE_PERIOD_MS (1000U)

#endif /* PH_CONFIG_H */
